config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post "message", to: "messages#create"
  get "signup", to: "users#new"
  post "signup", to: "users#create"

  mount ActionCable.server, at: '/cable'
end

app/models/active_users.rb
require 'set'

class ActiveUsers < ApplicationRecord
  @users = Set.new
  class << self
    def add(user_name)
      @users.add(user_name)
    end

    def remove(user_name)
      @users.delete(user_name)
    end

    def all
      @users.to_a
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @message = Message.new
    @messages = Message.custom_display
    @users = ActiveUsers.all
  end
end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", message: render_message(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial: "message", locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      ActiveUsers.add(current_user.username)
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "Incorrect username or password entered. Please try again."
      render "new"
    end
  end

  def destroy
    ActiveUsers.remove(current_user.username)
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to login_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(username: params[:session][:username], password: params[:session][:password])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the chatroom #{@user.username}"
      redirect_to root_path
    else
      flash[:alert] = "Failed to create new User Profile. Try a different username or password."
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h3 class="ui center aligned medium icon header">
  <i class="circular olive rocketchat icon"></i>
  Message Me
</h3>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="message-container">
                <div class="ui small feed" id="messages">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, url: message_path, html: { class: "ui reply form", role: "form" }, remote: true) do |f| %>
                    <div class="ui fluid icon input">
                        <%= f.text_field :body, placeholder: "Enter your message here...", autocomplete: :off %>
                        <%= f.button '<i class="bordered inverted olive icon edit"></i>'.html_safe %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="active-users-container">
                <table class="ui very basic collapsing celled table">
                    <thead>
                        <tr>
                            <th>Active Users:</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |username| %>
                            <tr>
                                <td>
                                    <h4 class="ui image header">
                                        <div class="content">
                                            <%= username %>
                                        </div>
                                    </h4>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
        <i class="close icon"></i>
        <div class="header"><%= message_content %></div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui olive inverted large menu">
    <% if logged_in? %>
        <%= link_to "Chatroom", root_path, class: "active item" %>
    <% end %>
    <div class="right menu">
        <% if logged_in? %>
            <div class="item">
                <%= link_to "Log out", logout_path, class: "ui primary button", method: :delete %>
            </div>
        <% else %>
            <div class="item">
                <%= link_to "Log in", login_path, class: "ui primary button" %>
            </div>
            <div class="item">
                <%= link_to "Sign up", signup_path, class: "ui primary button" %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em>: <%= message.body %>
        </div>
    </div>
</div> 

app/views/users/new.html.erb
<h3 class="ui center aligned medium icon header">
  <i class="circular olive power off icon"></i>
  Sign Up!
</h3>

<div class="ui middle aligned center aligned grid">
    <div class="six wide column">
        <div class="ui placeholder segment">
            <div class="ui very relaxed stackable grid left aligned column">
                <div class="column">
                    <%= form_for(:session, url: signup_path, html: { class: "ui form", role: "form" }, local: true, data: { turbo: false }) do |f| %>
                        <div class="field">
                            <%= f.label :username, "Username:" %>
                            <div class="ui left icon input">
                                <%= f.text_field :username, placeholder: "Username", autocomplete: :off %>
                                <i class="user icon"></i>
                            </div>
                        </div>
                        <div class="field">
                            <%= f.label :password, "Password:" %>
                            <div class="ui left icon input">
                                <%= f.text_field :password, placeholder: "Password", autocomplete: :off %>
                                <i class="lock icon"></i>
                            </div>
                        </div>
                        <%= f.submit "Sign up", class: "ui blue submit button" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>